apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: h3ndr1ch/gitopsfc
  newTag: 2543b99391bd3e82c383e2a6e57e5c3a9fe08e88
